php:
    build: php-fpm
    restart: always
    volumes:
        - /var/www:/var/www
    ports:
        - 9000:9000
    links :
        - db:db
        - maildev:maildev
nginx:
    image: nginx
    links:
        - php:php
        - phpmyadmin:phpmyadmin
        - maildev:maildev
    volumes:
        - /var/www:/var/www
        - /var/configuration/nginx/sites-enabled:/etc/nginx/sites-enabled
        - /var/configuration/nginx/nginx-conf/nginx.conf:/nginx.conf
        - /var/log/nginx:/var/log/nginx
    ports:
        - 80:80
    command: nginx -c /nginx.conf
db:
    image: mysql
    volumes:
        - /var/mysql:/var/lib/mysql
    environment:
        - MYSQL_ROOT_PASSWORD=root
maildev:
    image: djfarrelly/maildev
    ports:
        - "1080:80"
phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
        - db:db
    environment:
        PMA_ABSOLUTE_URI: http://phpmyadmin.localhost.dev/
    ports:
        - 8080:80
